import {esc,num,field,check,table,inputMark,inputNumber} from './format.js';
import {CLASS_IDS,CLASS_DESCRIPTIONS,VEHICLES,VEHICLE_CHOICES,WORKSHOPS,PLANNING_FIELDS,mixLabel} from './presets.js';
import {SCENARIOS} from './state.js';
import {dateText,slotStart,stamp} from './calendar.js';
export const select=(id,label,options,value)=>`<label class="field"><span>${inputMark(id)} ${label}</span><select data-field="${id}" data-input-ref="I-${inputNumber(id)}" id="${id}">${Object.entries(options).map(([k,v])=>`<option value="${esc(k)}" ${String(value)===k?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;
export const editCell=(path,value,type='number',step='any')=>`<label class="cell-field">${inputMark(path)}<input aria-label="Вхід I-${inputNumber(path)}" data-input-ref="I-${inputNumber(path)}" data-field="${esc(path)}" type="${type}" ${type==='number'?`step="${step}"`:''} value="${esc(value)}"></label>`;
const group=(id,title,body)=>`<article class="input-group" id="${id}"><h3>${title}</h3>${body}</article>`;
const defaults=(current,base,unit='')=>current===base?'':`<small class="default-hint edited">Типове значення: ${num(base)}${unit?' '+unit:''}. Змінено.</small>`;
export function profileInputs(s){return `<h3>1.1. Склад потоку й профіль СТО</h3><div class="field-grid">${select('vehiclePreset','Клас або змішаний потік',VEHICLE_CHOICES,s.vehiclePreset)}${select('workshopPreset','Профіль сервісу',Object.fromEntries(Object.entries(WORKSHOPS).map(([k,v])=>[k,v.label])),s.workshopPreset)}</div><p class="callout"><strong>${esc(mixLabel(s))}</strong><br>${esc(WORKSHOPS[s.workshopPreset].label)}</p><p>Вибір класу заповнює частки замовлень. Профіль СТО задає місячну програму, календар і ресурси. Усі числа можна уточнити в розділі 2.</p><div class="action-row"><button class="button button-small" data-action="restore-classes">Відновити типові характеристики класів</button><button class="button button-small" data-action="restore-workshop">Відновити типові дані СТО</button><button class="button button-small" data-action="undo-profile">Скасувати останню зміну профілю</button></div><p class="note">Початкові числа — навчальні припущення, а не норми виробника. Вибір іншого профілю СТО замінює його програму й ресурси; відредаговані характеристики класів та ваші записи зберігаються.</p>`;}
export function inputSections(d,diag,s,m){
 const author=`<div class="field-grid">${field('student','Студент / навчальний код',s.student,{type:'text'})}${field('group','Група',s.group,{type:'text'})}${field('variant','Назва варіанта',s.variant,{type:'text'})}</div><p class="note">Позначення <strong>I-…</strong> — номер вхідного поля: порядковий номер усередині розділу. Назва стовпця визначає величину й одиницю. Типові числа вже введено; підказка «Типове значення» з’являється лише після їх зміни.</p>`;
 const sum=CLASS_IDS.every(k=>Number.isFinite(s.vehicleMix[k]))?CLASS_IDS.reduce((n,k)=>n+s.vehicleMix[k],0):null;
 const valid=sum!==null&&Math.abs(sum-100)<1e-7&&CLASS_IDS.every(k=>s.vehicleMix[k]>=0&&s.vehicleMix[k]<=100);
 const mix=group('inputs-mix','2.1. Категорії автомобілів і частки замовлень',`${table('2.1','Категорії транспортних засобів і склад сервісного потоку',['Категорія','Призначення та місця','Максимальна маса категорії','Частка замовлень, %'],CLASS_IDS.map(k=>[k,`${esc(CLASS_DESCRIPTIONS[k].purpose)}<br><span class="note">${esc(CLASS_DESCRIPTIONS[k].seats)}</span>`,esc(CLASS_DESCRIPTIONS[k].mass),editCell('vehicleMix.'+k,s.vehicleMix[k])]))}<p class="note">Категорії визначено за статтею 4 Регламенту (ЄС) 2018/858 [S16]. Максимальна маса — повна маса автомобіля, не його вантажопідйомність. Фактичну масу вибраного автомобіля задають у таблиці 2.3.</p><div class="${valid?'callout':'error'}"><strong>Разом: ${num(sum)}% із 100%.</strong> ${valid?'Склад потоку придатний для розрахунку.':'Виправте частки або відновіть типовий склад потоку.'}<div class="action-row"><button class="button button-small" data-action="restore-mix">Відновити типові частки: ${s.vehiclePreset==='mixed'?'M1 50%, N1 30%, N2 20%':esc(s.vehiclePreset)+' 100%'}</button></div></div><p class="note">Частки стосуються замовлень на обслуговування. Однаковий склад потоку застосовано до всіх робіт і місяців. Клас із часткою 0% не впливає на результат. Зміна частки автоматично переносить різницю до / від сусіднього активного класу, зберігаючи разом 100%; якщо іншого активного класу немає — використовується наступний у таблиці.</p>`);
 const classes=group('inputs-classes','2.2. Трудомісткість і параметри автомобілів',`<p>Трудомісткість показує, скільки людино-годин потребує одне замовлення. Наприклад, 3 люд.-год — три години роботи одного працівника. Значення в таблицях 2.2–2.3 — редаговані навчальні приклади.</p>${table('2.2','Трудомісткість одного замовлення за категорією, люд.-год',['Клас',...d.job_types.map(j=>esc(j.name_uk))],CLASS_IDS.map(k=>[k,...d.job_types.map(j=>editCell('classData.'+k+'.hours.'+j.id,s.classData[k].hours[j.id])+defaults(s.classData[k].hours[j.id],VEHICLES[k].hours[j.id],'люд.-год'))]))}<p>Для кожного класу задайте один розрахунковий автомобіль. Його габарити й маса визначають вимоги до поста; радіус колеса використовується в окремій вправі ABS. Це характеристики вибраного автомобіля, а не межі категорії.</p>${table('2.3','Характеристики розрахункового автомобіля кожного класу',['Клас','Довжина, м','Ширина, м','Повна маса, т','Радіус колеса, м'],CLASS_IDS.map(k=>[k,...['length','width','mass','radius'].map(q=>editCell('classData.'+k+'.'+q,s.classData[k][q])+defaults(s.classData[k][q],VEHICLES[k][q],q==='mass'?'т':'м'))]))}`);
 const annual=group('inputs-annual','2.3. Річна програма й розподіл праці',`${table('2.4','Місячна кількість замовлень за видами робіт',['Місяць',...d.job_types.map(j=>esc(j.name_uk))],s.months.map((month,i)=>[i+1,...d.job_types.map(j=>editCell(`months.${i}.${j.id}`,month.counts[j.id],'number',1))]))}${table('2.5','Розподіл праці між постом та іншими дільницями',['Вид роботи','Частка на посту, 0–1','Частка поза постом'],d.job_types.map(j=>[esc(j.name_uk),editCell('bayShare.'+j.id,s.bayShare[j.id]),num(Number.isFinite(s.bayShare[j.id])?1-s.bayShare[j.id]:null)]))}<p class="note">Наприклад, 0,8 означає 80% праці на посту; 20% виконують на інших дільницях. Метод розподілу — [ST02], числові частки — навчальні припущення.</p>`);
 const planning=group('inputs-planning','2.4. Календар, ресурси, очікування та площа',`<div class="field-grid">${PLANNING_FIELDS.map(([k,label,unit,min,max,step])=>`<div>${field('planning.'+k,label+(unit?' · '+unit:''),s.planning[k],{min,max,step})}${defaults(s.planning[k],WORKSHOPS[s.workshopPreset].planning[k],unit)}</div>`).join('')}</div><p class="note">Фонд одного працівника не множиться на зміни СТО. Очікування задають у годинах роботи підприємства. Запаси навколо автомобіля й додаткова площа потрібні для попередньої оцінки приміщення.</p>`);
 const q=m.schedule,selected=q.orders.find(o=>o.id===s.selectedOrder);
 const reference=group('inputs-reference','2.5. Контрольний кейс: план робіт',`<p>Окрема вправа з 38 легковими замовленнями та 57 операціями. Її розклад не змінюється автоматично від складу змішаного потоку.</p><div class="field-grid">${select('scenario','Сценарій',SCENARIOS,s.scenario)}${field('partsReady','O29-01: деталі доступні з',stamp(slotStart(s.partsReady)),{type:'datetime-local'})}${select('day','День графіка',Object.fromEntries(Array.from({length:8},(_,i)=>[i,`Д${i+1} · ${dateText(slotStart(i*16)).split(',')[0]}`])),s.day)}${select('selectedOrder','Замовлення',Object.fromEntries(d.orders.map(o=>[o.id,o.id+' · '+o.scope_uk.slice(0,55)])),s.selectedOrder)}</div><p><strong>${esc(selected.id)}</strong> · ${esc(selected.vehicle_uk)} · ${esc(selected.scope_uk)}</p>${table('2.6','Операції вибраного замовлення та призначення ресурсів',['Операція','Зміст','Тривалість, год','Початок, дата / час','Пост','Працівник'],q.rows.filter(r=>r.orderId===s.selectedOrder).map(r=>[r.id,esc(r.op.name_uk),editCell('op.'+r.id+'.duration',r.duration===null?null:r.duration*.5,'number',.5),editCell('assignment.'+r.id+'.start_slot',stamp(slotStart(r.start)),'datetime-local'),select('assignment.'+r.id+'.bay_id','',Object.fromEntries(d.resources.bays.map(x=>[x.id,x.id])),r.bayId),select('assignment.'+r.id+'.staff_id','',Object.fromEntries(d.resources.staff.map(x=>[x.id,x.id])),r.staffId)]))}<p class="note">Час задається датою і годиною, тривалість — у годинах з кроком 0,5. Розрахунок використовує 30-хвилинні інтервали роботи. Операція не перетинає обід. Редагування призначення вмикає ручний сценарій; умова готовності деталей діє лише в ньому. B — пост, M — механік, W — працівник колісної дільниці, D — діагност.</p>`);
 const abs=group('inputs-abs','2.6. Діагностування одного автомобіля: ABS',`${select('diagnosticClass','Автомобіль для радіуса колеса',Object.fromEntries(CLASS_IDS.map(k=>[k,VEHICLES[k].label])),s.diagnosticClass)}<p class="note">Вибір переносить радіус із таблиці 2.3. Для ABS радіуси різних автомобілів не усереднюються.</p><div class="field-grid">${[['radius','Радіус r, м'],['z','Періодів на оберт z'],['limit','Навчальний поріг |δ|, %'],['frequency','Частота оцінки f, Гц'],['dr','Межа похибки Δr, м'],['df','Межа похибки Δf, Гц']].map(([k,label])=>field('abs.'+k,label,s.abs[k],{min:0})).join('')}</div>${table('2.7','Частота датчика правого переднього колеса до ремонту',['Вікно вимірювання','Частота FR, Гц'],diag.data.trace.map(r=>[r.sample,editCell('abs.frequencies.'+r.sample,Object.hasOwn(s.abs.frequencies,r.sample)?s.abs.frequencies[r.sample]:r.FR_Hz)]))}<p class="note">FR — праве переднє колесо. У початковому навчальному записі вікна 4 і 8 навмисно не мають виміру: це частина діагностичного завдання. Порожня клітинка означає «сигнал не записано», а не 0 Гц.</p>`);
 const adas=group('inputs-adas','2.7. Геометрія коліс та умови ADAS',`${[['required','Процедура виробника вимагає калібрування / скидання'],['oem','Є застосовна процедура виробника'],['equipment','Є потрібне обладнання'],['access','Є потрібний діагностичний доступ'],['trained','Є підготовлений працівник']].map(([k,label])=>check('adas.'+k,label,s.adas[k])).join('')}${select('adas.mode','Спосіб виконання',{outside:'Аутсорсинг',own:'Власними силами'},s.adas.mode)}<div class="field-grid">${[['start','Початок геометрії'],['due','Обіцяна готовність'],['available','Діагност доступний з']].map(([k,label])=>field('adas.'+k,label,s.adas[k],{type:'datetime-local'})).join('')}${[['alignment','Геометрія, год'],['procedure','Процедура, год'],['wait','Очікування / трансфер, год']].map(([k,label])=>field('adas.'+k,label,s.adas[k],{min:0})).join('')}</div><p class="note">ADAS — системи допомоги водієві; OEM — виробник автомобіля. Потребу в процедурі визначають для конкретної моделі [S14, S15].</p>`);
 const pilot=group('inputs-pilot','2.8. Журнал звернень СТО',`<p>Кожен рядок — одне звернення з кодом RQ. Для неприйнятого звернення вкажіть причину; порожній час означає, що подію не зафіксовано.</p>${table('2.8','Звернення та контрольні події',['Код','Прийнято','Прибуття','Початок','Обіцяно','Готовність','Видано'],s.pilot.map((r,i)=>[esc(r.id),select(`pilot.${i}.accepted`,'',{'true':'Так','false':'Ні'},String(r.accepted)),...['arrival','start','due','ready','issued'].map(k=>editCell(`pilot.${i}.${k}`,r[k],'datetime-local'))]))}${table('2.9','Праця, зайнятість та очікування за зверненням',['Код','Праця, люд.-год','Пост, посто-год','Очікування, год','Причина відмови / примітка','Дія'],s.pilot.map((r,i)=>[esc(r.id),...['labour','bay','wait'].map(k=>editCell(`pilot.${i}.${k}`,r[k])),editCell(`pilot.${i}.reason`,r.reason,'text'),`<button class="button button-small" data-remove-pilot="${i}">Видалити</button>`]))}<button class="button button-small" data-action="add-pilot">Додати звернення</button>`);
 const parking=group('inputs-parking','2.9. Стоянка поза робочими постами',`${table('2.10','Інтервали зайнятості місць очікування та видачі',['Звернення','Початок','Кінець','Причина','Дія'],s.parking.map((r,i)=>[editCell(`parking.${i}.orderId`,r.orderId,'text'),editCell(`parking.${i}.start`,r.start,'datetime-local'),editCell(`parking.${i}.end`,r.end,'datetime-local'),editCell(`parking.${i}.reason`,r.reason,'text'),`<button class="button button-small" data-remove-parking="${i}">Видалити</button>`]))}<button class="button button-small" data-action="add-parking">Додати інтервал</button><p class="note">Код звернення пов’язує стоянку з таблицями 2.8–2.9. Цей журнал визначає спостережений пік стоянки; річну потребу оцінює розділ 3.</p>`);
 const actions=`<div class="project-actions" id="project-actions"><h3>Збереження варіанта</h3><div class="action-row"><button class="button button-primary" data-action="save">Зберегти проєкт</button><button class="button" data-action="open">Відкрити проєкт</button><button class="button" data-action="reset">Новий навчальний приклад</button></div><p class="note">Новий приклад відновлює повний набір даних, придатний для розрахунку. Перед заміною збережіть свій варіант.</p></div>`;
 return author+mix+classes+annual+planning+reference+abs+adas+pilot+parking+actions;
}
