import {esc,num,table,formula,errorBox,inputNumber,arithmeticHtml} from './format.js';
import {CLASS_IDS,CLASS_DESCRIPTIONS,VEHICLES,WORKSHOPS,PLANNING_FIELDS,PRESET_VERSION,mixLabel} from './presets.js';
import {planningDiagram,capacityDiagram} from './diagrams.js';
const fig=(body,caption)=>`<figure class="figure">${body}<figcaption>${caption}</figcaption></figure>`;
export function planningInputsReport(data,s){return `<p><strong>Потік:</strong> ${esc(mixLabel(s))}.<br><strong>Профіль СТО:</strong> ${esc(WORKSHOPS[s.workshopPreset].label)}.</p><p class="note">Числа нижче — поточні прийняті входи. Типові значення є навчальними припущеннями. Частки замовлень однакові для всіх видів робіт і місяців.</p>${table('2.1','Категорії транспортних засобів і склад сервісного потоку',['Категорія','Місця, крім водія','Максимальна маса категорії','Частка, %'],CLASS_IDS.map(k=>[k,esc(CLASS_DESCRIPTIONS[k].seats),esc(CLASS_DESCRIPTIONS[k].mass),num(s.vehicleMix[k])]))}<p class="note">Категорії — за статтею 4 Регламенту (ЄС) 2018/858 [S16]. Маса категорії — повна маса, не вантажопідйомність.</p>${table('2.2','Трудомісткість одного замовлення за категорією, люд.-год',['Клас',...data.job_types.map(j=>esc(j.name_uk))],CLASS_IDS.map(k=>[k,...data.job_types.map(j=>num(s.classData[k].hours[j.id]))]))}${table('2.3','Характеристики розрахункового автомобіля кожного класу',['Клас','Довжина, м','Ширина, м','Повна маса, т','Радіус, м'],CLASS_IDS.map(k=>[k,...['length','width','mass','radius'].map(v=>num(s.classData[k][v]))]))}${table('2.4','Місячна кількість замовлень за видами робіт',['Місяць',...data.job_types.map(j=>esc(j.name_uk))],s.months.map((month,i)=>[i+1,...data.job_types.map(j=>num(month.counts[j.id]))]))}${table('2.5','Розподіл праці між постом та іншими дільницями',['Вид роботи','На посту, частка','Поза постом, частка'],data.job_types.map(j=>[esc(j.name_uk),num(s.bayShare[j.id]),num(1-s.bayShare[j.id])]))}${table('2.11','Прийняті календарні та ресурсні параметри',['Вхід','Умова','Значення','Одиниця'],PLANNING_FIELDS.map(([k,label,unit])=>['I-'+inputNumber('planning.'+k),esc(label),num(s.planning[k]),esc(unit)]))}`;}
export function planningResults(data,s,m){
 const f=m.fleet,y=m.annual,p=m.planning;if(p.error)return errorBox(f.error||y.error||p.error)+'<p><a href="#inputs-mix">Перевірити частки й вихідні дані в розділі 2 →</a></p>';
 const readable={bayLabour:'Σ (річна праця виду робіт × частка на посту)',benchLabour:'Річна праця − постова праця',bayHours:'Постова праця / працівників одночасно на посту',bayFund:'Дні × години зміни × зміни × частка активного фонду',workerFund:'Дні × години зміни × частка фонду працівника',bayDemand:'Посто-години / річний фонд поста',workerDemand:'Річні людино-години / фонд одного працівника',bayLoad:'100 × посто-години / (прийняті пости × фонд поста)',workerLoad:'100 × річна праця / (прийняті працівники × особистий фонд)',arrivalRate:'Річні замовлення / (дні × години зміни × зміни)',parkingDemand:'Нерівномірність × потік × (очікування до роботи + до видачі)',bayArea:'(Довжина + 2 × запас спереду/ззаду) × (ширина + 2 × бічний запас)',workArea:'Прийняті пости × площа поста + додаткова площа'};
 const cards=[['Пости',p.requiredBays,s.planning.plannedBays],['Працівники',p.requiredWorkers,s.planning.plannedWorkers],['Стоянка',p.requiredParking,s.planning.parkingSpaces]];
 return `<p class="callout">${esc(mixLabel(s))} → ${num(y.count)} замовлень → <strong>${num(y.hours,1)} люд.-год/рік</strong>. ${esc(WORKSHOPS[s.workshopPreset].label)}.</p>${table("3.1","Потрібні та прийняті ресурси СТО",['Ресурс','Розрахункова потреба, округлено вгору','Прийнято'],cards.map(([label,n,provided])=>[label,num(n,0),num(provided,0)]))}${p.warnings.length?p.warnings.map(errorBox).join(''):'<p class="callout">За введеними фондами ресурсів достатньо. Це агрегатна оцінка; конкретний календар і сумісність обладнання перевіряються окремо.</p>'}${formula('3.1','t<sub>j</sub> = Σ p<sub>c</sub> · t<sub>c,j</sub> / 100','p — частка замовлень класу, не частка парку. [SYN-02]')}${table("3.2","Обчислення середньої трудомісткості замовлення",['Вид роботи','Числова підстановка, люд.-год/замовлення','Результат'],data.job_types.map(j=>[esc(j.name_uk),f.active.map(k=>`${num(s.vehicleMix[k])} · ${num(s.classData[k].hours[j.id])} / 100`).join(' + '),num(f.hours[j.id],3)]))}${fig(planningDiagram(s,m),'Рисунок 3.1 — Від складу потоку до потреби в ресурсах.')}${fig(capacityDiagram(s,m),'Рисунок 3.2 — Розрахункова потреба та прийняті ресурси.')}<h3>Формули, підстановки та результати</h3>${table("3.3","Формули, числові підстановки та результати",['№','Величина','Формула → підстановка','Результат'],p.module.document.values.filter(v=>v.role==='calculation').map(v=>{
 const a=p.module.annotations[v.id],bindings=Object.fromEntries(v.expression.bindings.map(x=>[x.token,p.module.values[x.valueId]]));
 const substituted=arithmeticHtml(v.expression.source,bindings);
 return [`<span id="eq-${a.number}">(${a.number})</span>`,esc(a.label),`${esc(readable[v.id]||v.expression.source)}<br><span class="math-substitution">${substituted}</span>`,`${num(p.module.values[v.id],3)} ${esc(a.unit)}`];
 }))}<p class="note">Кількість постів, працівників і місць стоянки округлюється вгору. Чисельність — за фондом одного працівника, без множення його особистого фонду на зміни СТО. Поділ постової / позапостової праці спирається на [ST02]; числові частки задаються явно.</p><p class="note">Розрахунок посто-годин передбачає одночасну продуктивну роботу прийнятої кількості працівників на посту. Стоянка — оцінка через середній потік та задане очікування у відкриті години; коефіцієнт нерівномірності не гарантує фактичного піку. Ескізна площа ${num(p.workArea)} м² виключає територію стоянки й окремі не задані приміщення. Перевірка габаритів/маси є попередньою, не підтверджує точки підйому, оснащення чи монтаж.</p>`;
}
