import {stationPrintHtml} from './station-print.js';
import {planningInputsReport,planningResults} from './planning-view.js';
import {mixLabel,WORKSHOPS,PRESET_VERSION} from './presets.js';
import {esc,num,table,formula,linkReferences} from './format.js';
import {dateText,slotStart} from './calendar.js';
import {SCENARIOS,VERSION} from './state.js';
import {dependencyDiagram,orderDiagram,timeline,resourceChart,monthlyChart,planningDiagram,capacityDiagram} from './diagrams.js';
import {operationTable,renderSources,absFormulas,annualFormulas,adasFormulas,holdFormulas} from './views.js';
const paragraph=s=>`<p>${esc(s||'Не заповнено.')}</p>`;
const fig=(svg,caption)=>`<figure>${svg}<figcaption>${caption}</figcaption></figure>`;
export function reportBody(data,diag,s,m,sources){
 const q=m.schedule,a=m.abs,h=m.hold,ad=m.adas,y=m.annual,p=m.pilot;
 return `<header class="cover"><img src="assets/logo.svg" alt="Емблема коледжу"><p>Житомирський агротехнічний фаховий коледж<br><a href="https://zhatk.zt.ua/osvitnij-proczes/kafedri/kafedra-avtomobilnij-transport/">Кафедра «Автомобільного транспорту»</a></p><h1>Технічна експлуатація автомобілів</h1><h2>Розрахунок і організація роботи СТО</h2><p>Технічний звіт · ${esc(s.variant)}</p><p>Студент: ${esc(s.student||'не вказано')}<br>Група: ${esc(s.group||'не вказано')}<br>Потік: ${esc(mixLabel(s))}<br>Профіль: ${esc(WORKSHOPS[s.workshopPreset].label)}</p><p class="note">TEA ${VERSION} · сформовано ${dateText(Date.parse(m.evaluatedAt))}<br>База навчальних матеріалів: TEA 1.2.</p></header>
 <h2>1–2. Вибір профілю та вихідні дані</h2>${planningInputsReport(data,s)}
 <h2>3. Розрахунок ресурсів СТО</h2>${planningResults(data,s,m)}
 <h2>4. Контрольний кейс: вихідні умови</h2><p>Окремий кейс: 38 легкових замовлень; 57 операцій; чотири пости. Він не масштабується складом змішаного потоку. Сценарій ${SCENARIOS[s.scenario]}. Д1–Д5: 05–09.10.2026; 08–12 та 13–17; розрахунковий інтервал 0,5 год.</p>${paragraph(data.metadata.occupancy_model_uk)}<p>Ручна умова O29-01: деталі доступні з ${dateText(slotStart(s.partsReady))}${s.scenario!=='manual'?' (не застосовується в активному сценарії)':''}.</p>
 <h3>4.1. Навантаження контрольного кейсу</h3>${formula('4.1','H<sub>праці</sub> = Σ τ<sub>i</sub> · n<sub>i</sub>')}${formula('4.2','u<sub>r</sub> = H<sub>r</sub> / C<sub>r</sub> · 100%')}<p>Загальна трудомісткість: <strong>${num(q.summary.total)} люд.-год.</strong> Усі операції одноосібні, тому активна зайнятість постів має ту саму кількість годин. Очікування обліковується окремо.</p>${table("4.1","Попит і фонд часу ресурсів",['Ресурс','Попит, год','Фонд, год','Підстановка uᵣ','Зайнято в тижні'],q.resources.map(r=>[esc(r.id+' · '+r.name_uk),num(r.demand),num(r.capacity),`${num(r.demand)} / ${num(r.capacity)} · 100 = ${num(r.demand===null?null:r.demand/r.capacity*100,1)}%`,num(r.used)]))}${fig(resourceChart(q.resources),'Рисунок 4.1 — Попит і фонд часу ресурсів контрольного кейсу.')}
 <h3>4.2. Розклад, готовність і перевірки</h3><p class="${q.summary.valid?'note':'warning'}">${q.summary.valid?'Ресурсних порушень не виявлено.':`Порушення у ${q.summary.issueRows} операціях. Для відповідних замовлень готовність не підтверджено.`}</p>${table("4.4","Показники контрольного розкладу",['Показник','Результат'],[['Готові в першому тижні',`${q.summary.withinWeek} / 38`],['Вчасно',`${q.summary.onTime} / 38`],['Призначена праця в першому тижні',num(q.summary.delivered)+' люд.-год'],['Середній календарний час усіх 38 замовлень',num(q.summary.meanElapsed)+' год']])}${fig(timeline(q,s.day),`Рисунок 4.2 — Графік дня ${s.day+1}.`)}${fig(orderDiagram(q,s.selectedOrder),`Рисунок 4.3 — Послідовність ${s.selectedOrder}.`)}${formula('4.3','e<sub>i</sub> = s<sub>i</sub> + d<sub>i</sub>')}<p class="note">Числові підстановки для всіх операцій: тривалість у годинах = d · 0,5; кінець у інтервалах = s + d. Календарні дати враховують обід і вихідні.</p>${table("4.3","Розклад і перевірка всіх операцій",['ID','s + d = e, інтервали','d · 0,5, год','Пост / працівник','Кінець','Стан'],q.rows.map(r=>[r.id,`${num(r.start)} + ${num(r.duration)} = ${num(r.end)}`,`${num(r.duration)} · 0,5 = ${num(r.hours)}`,esc(r.bayId+' / '+r.staffId),dateText(r.endTime),esc(r.issues.join('; ')||'Коректно')]))}<h3>Готовність усіх замовлень</h3>${table("4.2","Готовність замовлень",['Замовлення','Обіцяно','Готовність','Статус'],q.orders.map(o=>[o.id,dateText(Date.parse(o.due_local+'Z')),dateText(o.ready),!o.valid?'Не підтверджено':o.onTime?'Вчасно':'Запізнення']))}
 <h2>5. Очікування на посту</h2>${holdFormulas(h)}${h.error?paragraph(h.error):!h.valid?paragraph('Не обчислено через некоректну послідовність O01.'):`<p>Окремий дослід: O01 займає ${esc(h.bayId)} після ремонту до контрольної операції. Додатково ${num(h.bayHours)} посто-год, ${num(h.calendarHours)} календарних годин. Конфліктних операцій: ${h.conflicts.length}.</p>${table("5.1","Конфлікти через очікування на посту",['Операція','Початок','Кінець'],h.conflicts.map(r=>[r.id,dateText(r.startTime),dateText(r.endTime)]))}<p class="note">Основний графік автоматично не змінено; потрібне перепланування перед висновком про нові строки. [B02, B03]</p>`}
 <h2>6. Діагностування ABS</h2>${paragraph(diag.student_case.complaint)}${table("6.2","Прийняті входи діагностування ABS",['Вхід','Значення'],[['r, м',num(s.abs.radius,4)],['z, періодів/оберт',num(s.abs.z)],['Навчальний поріг, %',num(s.abs.limit)],['f, Гц',num(s.abs.frequency)],['Δr, м',num(s.abs.dr,4)],['Δf, Гц',num(s.abs.df)]])}${absFormulas()}${a.error?paragraph(a.error):`<p>v = 3,6 · 2π · ${num(s.abs.radius)} · ${num(s.abs.frequency)} / ${num(s.abs.z)} = <strong>${num(a.nominal,3)} км/год</strong>. Граничний інтервал за ±Δr та ±Δf: <strong>${num(a.minimum,3)}–${num(a.maximum,3)} км/год</strong>.</p>${table("6.1","Порівняння сигналів ABS до та після ремонту",['Вікно','f опорна, Гц','FR, Гц','v FR, км/год','δ, %','Статус','δ після, %'],a.rows.map(r=>[r.sample,num(r.ref),num(r.FR_Hz),num(r.speed,3),num(r.delta,3),r.status,num(r.afterDelta,3)]))}<p>Неузгоджені вікна до роботи: ${a.bad}/12. Після роботи: ${a.afterBad}/12. Пропуск не замінено нульовою швидкістю.</p>`}<h3>Гіпотези й перевірки</h3>${paragraph(s.notes.hypotheses)}<h3>Докази та рішення</h3>${diag.data.evidence.map(e=>`<p class="note"><strong>${e.id}.</strong> ${esc(e.observation)}</p>`).join('')}${paragraph(s.notes.decision)}<h3>Контроль завершення</h3>${paragraph(s.notes.verification)}
 <h2>7. Річна програма</h2>${annualFormulas()}${table("7.2","Середні трудомісткості за складом потоку",['Вид робіт','Середня трудомісткість, люд.-год'],data.job_types.map(j=>[esc(j.name_uk),num(y.weightedHours?.[j.id])]))}${y.error?paragraph(y.error):`<p>${y.count} замовлень; ${num(y.hours,1)} люд.-год за рік.</p>${fig(monthlyChart(y.months),'Рисунок 7.1 — Сезонність трудомісткості.')}${table("7.1","Річна програма за місяцями",['Місяць',...data.job_types.map(j=>esc(j.name_uk)), 'Люд.-год'],y.months.map((r,i)=>[i+1,...data.job_types.map(j=>r.counts[j.id]),num(r.hours,1)]))}`}<p class="note">Річна програма — незалежний набір. Результати тижня не множаться на 52.</p>
 <h2>8. Геометрія коліс і ADAS</h2>${adasFormulas()}${table("8.1","Умови виконання геометрії та ADAS",['Параметр','Прийнято'],[['OEM-вимога',s.adas.required?'Так':'Ні'],['Виконання',s.adas.mode==='own'?'Власними силами':'Аутсорсинг'],['Початок геометрії',esc(s.adas.start)],['Геометрія, год',num(s.adas.alignment)],['Діагност доступний з',esc(s.adas.available)],['Процедура, год',num(s.adas.procedure)],['Очікування/трансфер, год',num(s.adas.wait)],['Процедура / обладнання / доступ / працівник',[s.adas.oem,s.adas.equipment,s.adas.access,s.adas.trained].map(x=>x?'Так':'Ні').join(' / ')]])}${ad.error?paragraph(ad.error):`<p>Готовність: ${dateText(ad.ready)}. Запізнення: ${num(ad.late)} год. ${ad.valid?'':'Власне виконання неможливе: не підтверджено всі передумови.'}</p>`}<p class="note">Самостійний модуль: до основного плану не включений. Часові значення — навчальні. [S14, S15]</p>
 <h2>9. Пілот СТО та стоянка</h2>${p.error?paragraph(p.error):`<p>Прийнято ${p.accepted} із ${p.total}; відмовлено ${p.rejected}. Праця ${num(p.labour)} люд.-год; зайнятість ${num(p.bay)} посто-год; очікування ${num(p.wait)} год. Вчасно ${p.onTime}/${p.accepted}, строки відомі для ${p.knownDeadlines}. Пік стоянки за журналом ${num(p.peak)} авто.</p>${p.errors.map(paragraph).join('')}${table("9.1","Результати пілотного журналу",['Код','Прийнято','Готовність','Праця','Пост','Очікування','Причина'],p.rows.map(r=>[esc(r.id),r.accepted?'Так':'Ні',dateText(r.readyMs),num(r.labour),num(r.bay),num(r.wait),esc(r.reason)]))}`}${table("9.2","Фізичні інтервали стоянки",['Авто','Початок стоянки','Кінець','Причина'],s.parking.map(r=>[esc(r.orderId),esc(r.start.replace('T',' ')),esc(r.end.replace('T',' ')),esc(r.reason)]))}<p class="note">Пік обчислено за точними межами записаних інтервалів; повнота фізичного журналу є умовою повноти показника.</p>
 <h2>10. Оснащення та висновок</h2>${paragraph(s.notes.equipment)}${paragraph(s.notes.conclusion)}<h2>Список використаних джерел</h2>${renderSources(sources)}<p class="note"></p>`;
}
export function schemesBody(data,s,m){return `<header class="sheet-head"><img src="assets/logo.svg" alt=""><div><p>Житомирський агротехнічний фаховий коледж · <a href="https://zhatk.zt.ua/osvitnij-proczes/kafedri/kafedra-avtomobilnij-transport/">Кафедра «Автомобільного транспорту»</a></p><h1>TEA — аркуш схем і розрахункових шляхів</h1><p>${esc(s.student||'Навчальний приклад')} · ${esc(s.group)} · ${esc(mixLabel(s))} · застосунок ${VERSION} / набори ${PRESET_VERSION}</p><p>${esc(WORKSHOPS[s.workshopPreset].label)} · ${esc(s.variant)}</p></div></header><div class="sheet-grid"><div>${fig(planningDiagram(s,m),'Рисунок 3.1 — Потік → річна праця → ресурси СТО.')}${fig(orderDiagram(m.schedule,s.selectedOrder),`Рисунок 4.3 — Окремий контрольний кейс: маршрут ${s.selectedOrder}.`)}</div><div>${fig(capacityDiagram(s,m),'Рисунок 3.2 — Розрахункова потреба та прийняті ресурси.')}${fig(timeline(m.schedule,s.day),`Рисунок 4.2 — Окремий контрольний кейс: графік дня ${s.day+1}.`)}</div></div><footer><strong>Основний розрахунок:</strong> ${m.planning.error?esc(m.planning.error):`${num(m.annual.hours,1)} люд.-год/рік; ${m.planning.requiredBays} постів; ${m.planning.requiredWorkers} працівників; оціночно ${m.planning.requiredParking} місць стоянки.`}<br>${m.planning.warnings?.length?esc(m.planning.warnings.join(' '))+'<br>':''}<strong>Контрольний кейс:</strong> ${m.schedule.summary.onTime}/38 вчасно; ${m.schedule.summary.issueRows} операцій із порушеннями. Класові й ресурсні початкові числа — навчальні припущення. Детальні входи, формули та джерела — у звіті.</footer>`;}
export function printHtml(type,data,diag,s,m,sources,base=''){
 if(s.design.workspace==='design')return stationPrintHtml(type,data,s,m,sources,base);
 const schemes=type==='schemes';
 return `<!doctype html><html lang="uk"><head><meta charset="utf-8"><base href="${esc(base)}"><title>TEA — ${schemes?'аркуш схем':'технічний звіт'}</title><link rel="stylesheet" href="assets/print.css"><style>@page{size:${schemes?'A3 landscape':'A4 portrait'};margin:${schemes?'10mm':'16mm 15mm 18mm'};@bottom-right{content:counter(page) ' / ' counter(pages);font:8pt Arial;color:#506871;}}</style></head><body class="${schemes?'schemes':'report'}"><div class="print-toolbar"><button onclick="window.print()">Друкувати / зберегти PDF</button><span>${schemes?'A3 · альбомний':'A4 · книжковий'} · 100% · вимкніть службові колонтитули браузера</span></div><main>${linkReferences(schemes?schemesBody(data,s,m):reportBody(data,diag,s,m,sources),sources)}</main></body></html>`;
}
export function printDocument(type,data,diag,s,m,sources){const popup=window.open('','_blank');if(!popup){alert('Дозвольте відкриття вікна для перегляду документа.');return;}popup.document.open();popup.document.write(printHtml(type,data,diag,s,m,sources,new URL('../',import.meta.url).href));popup.document.close();}
