import {postTypeLabel} from './station-layout.js';
import {esc,num,table,linkReferences} from './format.js';
import {VERSION} from './version.js';
import {stationInputs,programmeResults,resourceResults,equipmentResults,layoutResults,economicResults,sourceList,equipmentTable,roomTable,postEquipmentKey,openingTable,planLegendTable} from './station-view.js';
import {buildingDrawing,postDrawing} from './station-drawings.js';
const dept='Житомирський агротехнічний фаховий коледж · кафедра «Автомобільного транспорту»';
const deptLink='https://zhatk.zt.ua/osvitnij-proczes/kafedri/kafedra-avtomobilnij-transport/';
const h=(n,t)=>`<h2>${n}. ${t}</h2>`;
export function stationReport(data,s,m,sources){const r=m.station,i=stationInputs(data,s,r,true);return `<header class="cover"><img src="assets/logo.svg" alt="Емблема коледжу"><p><a href="${deptLink}">${dept}</a></p><h1>Технологічний проєкт станції</h1><h2>Технічна експлуатація автомобілів</h2><p>${esc(s.variant)}</p><p>Студент: ${esc(s.student||'Навчальний приклад')}<br>Група: ${esc(s.group||'—')}</p><p>TEA ${VERSION} · ${esc(m.evaluatedAt.slice(0,10))}<br>${s.design.programme==='atp'?'Власний парк АТП':'Комерційна СТО'} · ${s.design.mode==='new'?'проєктування нової станції':'перевірка наявної станції'}</p></header>`+h(1,'Завдання і режим')+i.intro+h(2,'Вихідні дані')+i.body+h(3,'Виробнича програма')+programmeResults(data,s,r)+h(4,'Пости та працівники')+resourceResults(s,r)+h(5,'Оснащення')+equipmentResults(s,r)+'<section class="report-layout">'+h(6,'План корпусу і робочого поста')+layoutResults(s,r)+'</section>'+h(7,'Економічне порівняння')+economicResults(s,r)+h('Д','Список використаних джерел')+sourceList(sources);}
function stamp(s,r,no,scale,title){
 const rows=[['Розробив',s.student||'Навчальний приклад'],['Перевірив',''],['Група',s.group||'—']];
 const tx=(x,y,t,size=2.5,anchor='middle')=>`<text x="${x}" y="${y}" font-size="${size}" text-anchor="${anchor}">${esc(t)}</text>`;
  const cut=(t,n)=>t.length>n?t.slice(0,n-1)+'…':t;
 let grid='<rect x=".2" y=".2" width="184.6" height="54.6" fill="white"/><path d="M65 0V55M65 10H185M0 25H185M65 40H185M135 25V55M150 25V40M165 25V40M135 30H185"/>';
 for(const x of [10,20,30,40,55])grid+=`<path d="M${x} 0V25"/>`;
 for(const y of [5,10,15,20,30,35,40,45,50])grid+=`<path d="M0 ${y}H65"/>`;
 for(const x of [17,40,55])grid+=`<path d="M${x} 25V55"/>`;
 const labels=['Зм.','Кільк.','Арк.','№ док.','Підп.','Дата'];
 let labelsSvg=labels.map((v,i)=>tx([5,15,25,35,47.5,60][i],23.5,v,2)).join('');
 labelsSvg+=rows.map(([a,b],i)=>tx(1,29+i*5,a,2,'start')+tx(18,29+i*5,cut(b,17),2,'start')).join('');
 labelsSvg+=tx(125,6.5,`TEA-${VERSION}-ТХ-${String(no).padStart(2,'0')}`,3)+tx(125,17,'Технологічний проєкт станції',3)+tx(125,22,cut(s.variant,68),2.5)+tx(100,34,`Корпус ${num(r.layout.plan.outerWidth)} × ${num(r.layout.plan.outerDepth)} м`,2.5)+tx(100,38,`Масштаб 1:${scale}`,2.5);
 labelsSvg+=tx(142.5,28.4,'Стадія',2)+tx(157.5,28.4,'Аркуш',2)+tx(175,28.4,'Аркушів',2)+tx(142.5,36,'НП*',3)+tx(157.5,36,no,3)+tx(175,36,'2',3);
 const titleLines=title==='План виробничого корпусу'?['План виробничого','корпусу']:['План оснащення','робочого поста'];
 labelsSvg+=tx(100,46,titleLines[0],3)+tx(100,51,titleLines[1],3)+tx(160,46,'ЖАТФК',3)+tx(160,51,'Автомобільний транспорт',2.2);
 return `<div class="drawing-credit"><img src="assets/logo.svg" alt="Емблема коледжу"><div><a href="${deptLink}">${dept}</a><br>TEA ${VERSION} · навчальне технологічне компонування · розміри в мм<br>*НП — навчальний проєкт. Основний напис: адаптація форми Г.1; рамка: додаток Д ДСТУ 9243.4:2023 [S26].</div></div><footer class="drawing-stamp"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 185 55" width="185mm" height="55mm" role="img" aria-label="Основний напис аркуша ${no}" font-family="Arial" fill="#222"><g stroke="#222" stroke-width=".25">${grid}</g>${labelsSvg}</svg></footer><span class="sheet-format">Формат A1 · 841 × 594 мм</span>`;
}
export function stationSheets(s,r){
 if(r.error)return `<h1>Креслення не сформовано</h1><p>${esc(r.error)}</p>`;
 const a=buildingDrawing(r,{print:true}),b=postDrawing(r,s.design.selectedBay,{print:true}),l=r.layout;
 const zoneTable=table('А1.2','Експлікація виробничих зон',['Зона / тип','Пости','Праця, люд.-год/рік','Габарит поста, м'],r.zones.map(g=>[esc(g.label)+'<br>'+postTypeLabel(g),l.bays.filter(x=>x.zoneKey===g.key).map(x=>x.id).join(', '),num(g.labour),`${num(g.w)} × ${num(g.l)}`]));
 const characteristics=table('А1.1','Основні характеристики',['Показник','Значення'],[['Зовнішній габарит',`${num(l.plan.outerWidth)} × ${num(l.plan.outerDepth)} м`],['Внутрішня площа / вільна висота',`${num(r.economics.area)} м² / ${num(l.height)} м`],['Робочі пости / штат',`${l.bays.length} / ${r.workers} виробничих + ${s.design.admin} адміністративних`],['Проїзні / тупикові',`${l.selection.through} / ${l.selection.reverse}`],['Потужність обладнання',`${num(r.economics.connectedPower)} кВт`],['Очікування поза корпусом',`${r.parking} місць (до генплану)`],['Бюджет інвестицій',`${num(r.economics.capital,0)} грн`]]);
 const equipmentSummary=table('А1.4','Зведене оснащення',['Найменування','Кількість комплектів','Позиції на плані'],Object.values(r.equipment.reduce((a,e)=>{a[e.id]??={name:e.name,n:0,positions:[]};a[e.id].n++;a[e.id].positions.push(e.pos);return a;},{})).map(e=>[esc(e.name),e.n,e.positions.join(', ')]));
 const notes=`<p>Умовні позначення: пунктир — габарит ТЗ; коло — позиція обладнання; П01… — пости (ТО/ПР — обслуговування й ремонт, Д — діагностика, Ш — шини); 001–005 — приміщення; підкреслені числа — площі кімнат у м²; ВР — ворота, Д — двері, ВК — вікна. Стрілка — напрям заїзду. Сіре поле — проїзд. Усі розміри — мм.</p><p>Компонування незалежних постів: [S17, S30, S31]. Вибір із ${l.selection.evaluated} варіантів: вписування → мінімум тупикових постів для ТЗ від ${num(l.selection.threshold)} м → мінімум площі. Прийнято до ${l.columns} постів у ряду. Поріг довжини — проєктне припущення. ${l.selection.manualCoordinates?'Після добору накладено ручні координати.':''} Стіни та прорізи — [S27]. Площі — між гранями перегородок, без дверних ніш; площа залу 005 включає проїзди. Категорії пожежної небезпеки не визначено. Товщини й допоміжні площі прийняті для ескізу; траєкторії поворотів, конструкції, фундаменти та інженерні системи уточнюють окремим проєктом. Ціни — введений бюджет [SYN-03].</p>`;
 const warnings=r.warnings.length?`<p class="warning">Зауваження: ${r.warnings.map(esc).join(' ')}</p>`:'<p>За введеними умовами річний фонд постів і персоналу достатній; перевірка маси підіймачів пройдена.</p>';
 return `<article class="a1-page"><div class="drawing-frame"><h1>Виробничий корпус · технологічний план</h1><div class="a1-content"><figure class="a1-drawing">${a.html}<figcaption>Рисунок А1.1 — План корпусу. Масштаб 1:${a.scale} за друку 100%.</figcaption></figure><aside>${characteristics}${zoneTable}${roomTable(r,'А1.3')}${equipmentSummary}${openingTable(r,'А1.5')}${planLegendTable(r,'А1.6')}${notes}${warnings}</aside></div>${stamp(s,r,1,a.scale,'План виробничого корпусу')}</div></article><article class="a1-page"><div class="drawing-frame"><h1>${esc(b.bay?.id||'Пост')} · оснащення і технологічний маршрут</h1><div class="a1-content detail-sheet"><figure class="a1-drawing">${b.html}<figcaption>Рисунок А2.1 — Оснащений пост. Масштаб 1:${b.scale} за друку 100%.</figcaption></figure><aside>${b.bay?postEquipmentKey(b.bay,'А2.1'):''}${table('А2.2','Характеристики робочого поста',['Параметр','Значення'],b.bay?[["Призначення",esc(b.bay.label)],["Тип / виїзд",postTypeLabel(b.bay)],['Розмір',`${num(b.bay.w)} × ${num(b.bay.l)} м`],['Габарит ТЗ',`${num(b.bay.vehicle.length)} × ${num(b.bay.vehicle.width)} × ${num(b.bay.vehicle.height)} м`],['Маса / максимальна вісь',`${num(b.bay.vehicle.mass)} / ${num(b.bay.vehicle.axle)} т`],['Одночасно працюють',s.design.crew],['Вільна висота',num(b.bay.height)+' м']]:[])}${planLegendTable(r,'А2.3')}${table('А2.4','Послідовність робіт',['Етап','Операція'],[['1','Приймання та ідентифікація автомобіля'],['2','Встановлення на пост; перевірка придатності оснащення'],['3',esc(b.bay?.label??'Виконання робіт')],['4','Контроль якості; '+(b.bay?.access==='through'?'виїзд через протилежний торець переднім ходом':'виїзд заднім ходом до проїзду')]])}<p>Номери позицій ті самі, що на аркуші 1 та у звіті A4. Символи устаткування позначають місце розміщення, не монтажні отвори. Підводи — вода, стиснене повітря, 230 / 400 В; мережі прокладають над робочою зоною. Їх типорозміри та захист визначають окремим розрахунком. Чотири мобільні колони — одна позиція комплекту.</p><p>Параметри виробника: [S23, S24]. Підіймання потребує перевірки точок підхоплення, кожного колеса, колісної бази та основи. Прямокутник шинного комплекту — сумарна робоча зона двох верстатів. Повні джерела й припущення наведено у звіті.</p>${warnings}</aside></div>${stamp(s,r,2,b.scale,'План оснащення робочого поста')}</div></article>`;
}
export function stationPrintHtml(type,data,s,m,sources,base=''){
 const schemes=type==='schemes';return `<!doctype html><html lang="uk"><head><meta charset="utf-8"><base href="${esc(base)}"><title>TEA ${VERSION} — ${schemes?'комплект креслень A1':'технічний звіт A4'}</title><link rel="stylesheet" href="assets/print.css"><style>@page{size:${schemes?'841mm 594mm':'A4 portrait'};margin:${schemes?'0':'16mm 15mm 18mm'};${schemes?'':'@bottom-right{content:counter(page) " / " counter(pages);font:8pt Arial;color:#506871;}'}}</style></head><body class="${schemes?'station-sheets':'report station-report'}"><div class="print-toolbar"><button onclick="window.print()">Друкувати / зберегти PDF</button><span>${schemes?'A1 · 841 × 594 мм · 2 аркуші':'A4 · технічний звіт'} · масштаб 100% · вимкніть колонтитули браузера · перевірте формат паперу в діалозі друку</span></div><main>${linkReferences(schemes?stationSheets(s,m.station):stationReport(data,s,m,sources),sources)}</main></body></html>`;
}
