import {renderStationPages} from './station-view.js';
import {esc,num,table,badge,formula,field,check,errorBox,inputMark,inputNumber,linkReferences,flattenInputNumbers} from './format.js';
import {dateText,slotStart,slotEnd} from './calendar.js';
import {SCENARIOS} from './state.js';
import {VERSION,PRESET_VERSION} from './version.js';
import {profileInputs,inputSections} from './inputs.js';
import {planningResults} from './planning-view.js';
import {dependencyDiagram,orderDiagram,timeline,resourceChart,monthlyChart} from './diagrams.js';
export const heading=(n,title,sub='')=>`<div class="section-heading"><div class="section-index">${n}</div><div><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div></div>`;
export const section=(id,n,title,sub,body)=>`<section class="section" id="${id}">${heading(n,title,sub)}${body}</section>`;
export const kpis=items=>`<div class="kpis">${items.map(([n,l])=>`<div class="kpi"><strong>${n}</strong><span>${l}</span></div>`).join('')}</div>`;
const select=(id,label,options,value,number='')=>`<label class="field"><span><small>${number}</small> ${label}</span><select data-field="${id}" id="${id}">${Object.entries(options).map(([k,v])=>`<option value="${esc(k)}" ${String(value)===k?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;
const fig=(body,caption)=>`<figure class="figure">${body}<figcaption>${caption}</figcaption></figure>`;
const noteField=(key,label,s)=>`<label class="field"><span>${inputMark("notes."+key)} ${label}</span><textarea data-input-ref="I-${inputNumber("notes."+key)}" data-field="notes.${key}" maxlength="12000">${esc(s.notes[key])}</textarea></label>`;
const editCell=(path,value,type='number')=>`<input aria-label="${esc(path)}" data-field="${esc(path)}" type="${type}" ${type==='number'?'step="any"':''} value="${esc(value)}">`;

export function renderPages(d,diag,s,m,sources){
 if(s.design.workspace==='design')return renderStationPages(d,s,m,sources);
 return flattenInputNumbers(renderExercisePages(d,diag,s,m,sources));
}
export function renderExercisePages(d,diag,s,m,sources){
 const {schedule:q,abs:a,hold:h,adas:ad,annual:y,pilot:p}=m,summary=q.summary;
 const intro=`<section class="section" id="intro"><div class="hero"><div><p class="eyebrow">Технічна експлуатація автомобілів</p><h1>Розрахунок і організація роботи СТО</h1><p class="lead">Від вихідних даних до обґрунтованого рішення: навантаження ресурсів, розклад робіт, діагностування та контроль готовності.</p><div class="hero-links"><a href="https://zhatk.zt.ua/" target="_blank" rel="noopener">Офіційний сайт ЖАТФК ↗</a><a href="https://zhatk.zt.ua/osvitnij-proczes/kafedri/kafedra-avtomobilnij-transport/" target="_blank" rel="noopener">Кафедра «Автомобільного транспорту» ↗</a></div></div><div class="hero-mark"><img src="assets/logo.svg" alt="Емблема Житомирського агротехнічного фахового коледжу"></div></div><div class="principles"><div class="principle"><strong>Формула → підстановка → результат</strong><span>Числа, одиниці та припущення можна перевірити в кожному розділі.</span></div><div class="principle"><strong>Праця, зайнятість і очікування</strong><span>Різні величини мають різний зміст і не підміняють одна одну.</span></div><div class="principle"><strong>Нумерація та джерела</strong><span>Номери входів, таблиць, формул і рисунків забезпечують однозначні посилання.</span></div></div><h3>1. Маршрут виконання</h3><ol class="steps"><li>Оберіть клас / змішаний потік і профіль СТО.</li><li>Перевірте всі входи в розділі 2 та результати від розділу 3.</li><li>Обґрунтуйте рішення за доказами й перевірками.</li><li>Збережіть проєкт, звіт і аркуш схем.</li></ol>${profileInputs(s)}<p class="note">Усі строки, тривалості та виміри навчального прикладу синтетичні. Методичні джерела не замінюють документацію конкретного автомобіля.</p></section>`;
 const project=section('project',2,'Вихідні дані та прийняті припущення','Усі числові входи зібрано тут; подальші розділи показують розрахунок.',inputSections(d,diag,s,m));
 const resources=section('resources',3,'Розрахунок ресурсів СТО','Склад потоку → річна праця → пости, працівники та стоянка.',planningResults(d,s,m));
 const selected=q.orders.find(o=>o.id===s.selectedOrder);
 const schedule=section('schedule',4,'Контрольний кейс: розклад і шлях операцій','Окремі 38 замовлень / 57 операцій з вихідного пакета. Редагування — у розділі 2.5.',`<p><a href="#inputs-reference">Змінити призначення, замовлення або день → 2.5</a></p>${formula('4.1','H<sub>праці</sub> = Σ τ<sub>i</sub> · n<sub>i</sub>','Для контрольного кейсу nᵢ = 1. [CASE]')}${formula('4.2','u<sub>r</sub> = H<sub>r</sub> / C<sub>r</sub> · 100%')}${fig(resourceChart(q.resources),'Рисунок 4.1 — Ресурси контрольного кейсу.')}<p class="${summary.valid?'callout':'error'}">${summary.valid?'Призначення не мають ресурсних порушень.':`Порушення у ${summary.issueRows} операціях; відповідна готовність не підтверджена.`}</p>${fig(timeline(q,s.day),'Рисунок 4.2 — Зайнятість постів і працівників за вибраний день.')}${fig(orderDiagram(q,s.selectedOrder),'Рисунок 4.3 — Маршрут вибраного замовлення.')}<p><strong>${esc(selected.id)}</strong> · ${esc(selected.scope_uk)}.</p>${formula('4.3','e<sub>i</sub> = s<sub>i</sub> + d<sub>i</sub>','Тривалість вимірюється у 30-хвилинних робочих інтервалах; на графіку і у таблицях показано дату та час.')}${kpis([[summary.withinWeek,'замовлень завершено за тиждень'],[summary.onTime+' / 38','замовлень вчасно'],[num(summary.delivered),'людино-годин у першому тижні'],[num(summary.meanElapsed),'середній календарний час, год']])}<div class="subsection"><h3>Ресурси та всі строки</h3>${table("4.1","Попит і фонд часу ресурсів",['Ресурс','Попит, год','Фонд, год','Зайнято в тижні'],q.resources.map(r=>[r.id,num(r.demand),num(r.capacity),num(r.used)]))}${table("4.2","Готовність замовлень",['Замовлення','Обіцяно','Готовність','Статус'],q.orders.map(o=>[o.id,dateText(Date.parse(o.due_local+'Z')),dateText(o.ready),!o.valid?'Порушення':o.onTime?'Вчасно':'Запізнення']))}</div><div class="subsection"><h3>Усі операції</h3>${operationTable(q)}</div><p class="note">Автоматичний пошук оптимального плану не виконується. Зміна профілю основного розрахунку не змінює календар цього окремого кейсу.</p>`);
 const waiting=section('waiting',5,'Очікування на робочому посту','Окремий дослід: O01 залишається на ремонтному посту до початку контрольної операції.',h.error?errorBox(h.error):!h.valid?errorBox('Спочатку задайте коректну послідовність O01.'): `${holdFormulas(h)}${kpis([[num(h.bayHours),'додаткових посто-годин очікування'],[num(h.calendarHours),'календарних годин очікування'],[h.bayId,'зайнятий пост'],[h.conflicts.length,'операцій, що конфліктують']])}${table("5.1","Конфлікти через очікування на посту",['Конфліктна операція','Пост','Початок','Кінець'],h.conflicts.map(r=>[r.id,r.bayId,dateText(r.startTime),dateText(r.endTime)]))}<p class="warning">Цей дослід не змінює основний план автоматично. За наявності конфліктів новий строк готовності не підтверджено: потрібне перепланування.</p>`);
 const abs=section('abs',6,'Діагностування ABS','Від числового запису до рішення, підтвердженого доказами.',`<p>${esc(diag.student_case.complaint)}</p><p class="note">${esc(diag.data.conditions)}</p><p><a href="#inputs-abs">Змінити вхідні значення → 2.6</a></p>${absFormulas()}${a.error?errorBox(a.error):`${kpis([[num(a.nominal,3),'номінальна швидкість, км/год'],[`${num(a.minimum,3)}–${num(a.maximum,3)}`,'граничний інтервал, км/год'],[`${a.bad} / 12`,'неузгоджених вікон до ремонту'],[`${a.afterBad} / 12`,'неузгоджених вікон після ремонту']])}${table("6.1","Порівняння сигналів ABS до та після ремонту",['Вікно','f опорна, Гц','FR, Гц','v FR, км/год','δ, %','Статус','δ після, %'],a.rows.map(r=>[r.sample,num(r.ref),num(r.FR_Hz),num(r.speed,3),num(r.delta,3),badge(r.status,r.status==='Узгоджено'?'':'warn'),num(r.afterDelta,3)]))}`}${noteField('hypotheses','Гіпотези та перевірки, що їх розділяють',s)}<div class="subsection"><h3>Докази діагностування E1–E6</h3>${diag.data.evidence.map(e=>`<p><strong>${e.id}.</strong> ${esc(e.observation)}</p>`).join('')}</div>${noteField('decision','Рішення: доказ → робота → контроль',s)}<div class="subsection"><h3>Записи перевірки після роботи V1–V4</h3>${diag.data.verification.map(e=>`<p><strong>${esc(e.id)}.</strong> ${esc(e.observation??e.result??e.description)}</p>`).join('')}</div>${noteField('verification','Критерії завершення та обмеження висновку',s)}<p class="warning">5% — критерій цього навчального запису. Він не є універсальним допуском ABS або дозволом експлуатації. Частка неузгоджених вікон не є ймовірністю відмови парку.</p>`);
 const annual=section('annual',7,'Річна програма та сезонність','Поточний склад потоку і місячні кількості з розділу 2.',`<p><a href="#inputs-annual">Змінити програму → 2.3</a></p>${annualFormulas()}${y.error?errorBox(y.error):`${kpis([[y.count,'замовлень за рік'],[num(y.hours,1),'людино-годин за рік'],['12','місяців'],['Зважені','трудомісткості за потоком']])}${fig(monthlyChart(y.months),'Рисунок 7.1 — Місячна трудомісткість.')}${table("7.1","Річна програма за місяцями",['Місяць',...d.job_types.map(j=>esc(j.name_uk)),'Люд.-год'],y.months.map((r,i)=>[i+1,...d.job_types.map(j=>r.counts[j.id]),num(r.hours,1)]))}`}`);
 const adas=section('adas',8,'Геометрія коліс і ADAS','Умовна OEM-вимога, власна спроможність або аутсорсинг.',`<p><a href="#inputs-adas">Змінити умови → 2.7</a></p>${adasFormulas()}${ad.error?errorBox(ad.error):!ad.valid?errorBox('Власне виконання неможливе: не підтверджено всі передумови.'):kpis([[dateText(ad.alignmentEnd),'кінець геометрії'],[dateText(ad.ready),'розрахункова готовність'],[num(ad.late),'годин запізнення'],[ad.feasible?'Так':'Ні','власна спроможність підтверджена']])}<p class="warning">Це окремий навчальний модуль. Його години не додаються до 57 операцій автоматично. Навіть достатній тижневий фонд D1 і B3 не доводить, що вони вільні одночасно у вибраний час.</p>`);
 const pilot=section('pilot',9,'Пілот СТО та стоянка','Редагуйте синтетичні приклади або внесіть дозволені знеособлені записи.',`<p class="note">Поля звернення ідентифікуються його кодом. Порожнє поле означає «невідомо». Підсумки праці й зайнятості охоплюють лише прийняті звернення.</p>${p.error?errorBox(p.error):`${p.errors.map(errorBox).join('')}${kpis([[`${p.accepted} / ${p.total}`,'прийнятих звернень'],[num(p.labour),'людино-годин'],[num(p.bay),'посто-годин'],[num(p.peak),'пік стоянки за журналом, авто']])}<p>Очікування: <strong>${num(p.wait)} год</strong>. Вчасно: <strong>${p.onTime} / ${p.accepted}</strong>; строки відомі для ${p.knownDeadlines} з ${p.accepted} прийнятих звернень.</p>`}${p.error?'':table("9.1","Результати пілотного журналу",['Код','Прийнято','Готовність','Праця, год','Пост, год','Очікування, год'],p.rows.map(r=>[esc(r.id),r.accepted?'Так':'Ні',dateText(r.readyMs),num(r.labour),num(r.bay),num(r.wait)]))}<p><a href="#inputs-pilot">Редагувати журнали → 2.8</a></p><p class="note">Пік за цим журналом не є фактичним піком усієї річної програми. Для прогнозної стоянки використовуйте розділ 3.</p>`);
 const conclusion=section('conclusion',10,'Оснащення та обґрунтований висновок','Зв’язок ресурсу, операції та підтвердженої придатності.',`${table("10.1","Оснащення та перевірка придатності",['Група','Позиція','Що підтвердити'],diag.equipment.items.map(e=>[esc(e.group),esc(e.position),esc(e.selection_checks)]))}<p class="note">${esc(diag.equipment.layout_boundary)}</p>${noteField('equipment','Матриця «потрібно — дозволяє обладнання — підтвердження / відсутні дані»',s)}<h3>Висновок за поточним варіантом</h3>${noteField('conclusion','Обмеження, запропоновані зміни та очікуваний результат',s)}<div class="subsection"><h3>Додаткові методичні матеріали</h3><p><a href="docs/STUDENT_GUIDE_UA.md" target="_blank">Основні студентські вказівки</a> · <a href="docs/INSTRUCTOR_GUIDE_UA.md" target="_blank">Викладацький ключ основного кейсу</a> · <a href="docs/SOURCES_UA.md" target="_blank">Повний реєстр джерел TEA 1.2</a></p><p class="note">Посібники основного кейсу з архіву 1.1; нові модулі 1.2 включено безпосередньо до застосунку. Ключ викладача є відкритим навчальним матеріалом, а не захищеною системою оцінювання.</p></div>`);
 const refs=section('sources','Д','Список використаних джерел','Бібліографічні посилання за ДСТУ 8302:2015.',renderSources(sources));
 const exports=section('exports','PDF','Звіт і аркуш схем','Обидва документи відтворюють поточний стан розрахунку.',`<div class="split"><div class="export-card"><span class="export-number">01 / ТЕХНІЧНИЙ ЗВІТ</span><h3>Розрахунок та обґрунтування</h3><p>Вихідні дані, формули, числові результати, перевірки, рішення, рисунки й джерела. Формат A4.</p><button class="button button-primary" data-action="report">Відкрити звіт / PDF</button></div><div class="export-card"><span class="export-number">02 / АРКУШ СХЕМ</span><h3>Шляхи та взаємозв’язки</h3><p>Шлях розрахунку змішаного потоку, потреба в ресурсах та приклад маршруту / графіка. Формат A3, альбомний.</p><button class="button button-primary" data-action="schemes">Відкрити аркуш схем / PDF</button></div></div><p class="note">Відкриється окрема сторінка для перегляду. Натисніть «Друкувати / PDF» і виберіть «Зберегти як PDF». Масштаб 100%, без службових колонтитулів браузера. Для продовження редагування збережіть проєкт у розділі 2.</p>`);
 return linkReferences(intro+project+resources+schedule+waiting+abs+annual+adas+pilot+conclusion+refs+exports,sources);
}
export function operationTable(q){return table("4.3","Розклад усіх операцій",['ID','Початок','Кінець','Пост / працівник','Праця, год','Стан'],q.rows.map(r=>[r.id,dateText(r.startTime),dateText(r.endTime),esc(r.bayId+' / '+r.staffId),num(r.hours),r.issues.length?esc(r.issues.join('; ')):'Коректно']),'compact');}
export function renderSources(sources){return `<ol class="reference-list">${sources.map((r,i)=>`<li id="source-${i+1}"><span class="reference-number">[${i+1}]</span> <span>${esc(r.bibliography||r.title)}${r.url?` URL: <a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.url)}</a>.${r.access_date?` (дата звернення: ${r.access_date.split('-').reverse().join('.')}).`:''}`:''}</span></li>`).join('')}</ol>`;}

export const absFormulas=()=>`${formula('6.1','C = 2πr','C — шлях колеса за один оберт, м.')}${formula('6.2','k = 3,6 · C / z','k — коефіцієнт перетворення частоти на швидкість.')}${formula('6.3','v = kf = 3,6 · 2πrf / z','r — м; f — Гц; v — км/год. [S01]')}${formula('6.4','v<sub>min</sub> = 3,6 · 2π(r − Δr)(f − Δf) / z')}${formula('6.5','v<sub>max</sub> = 3,6 · 2π(r + Δr)(f + Δf) / z')}${formula('6.6','f<sub>оп</sub> = median(f<sub>FL</sub>, f<sub>RL</sub>, f<sub>RR</sub>)','Опорна частота — медіана трьох інших коліс.')}${formula('6.7','δ = 100 · (f<sub>FR</sub> − f<sub>оп</sub>) / f<sub>оп</sub>','δ — відхилення правого переднього колеса, %. Та сама формула використовується після ремонту.')}`;
export const annualFormulas=()=>`${formula('7.1','H<sub>m</sub> = Σ N<sub>m,j</sub> · t<sub>j</sub>','Місячна праця: кількість замовлень × середня трудомісткість.')}${formula('7.2','H<sub>рік</sub> = Σ H<sub>m</sub>','Сума за 12 місяців, люд.-год.')}${formula('7.3','H<sub>j</sub> = N<sub>рік,j</sub> · t<sub>j</sub>','Річна праця окремого виду робіт, люд.-год.')}`;
export const adasFormulas=()=>`${formula('8.1','t<sub>геом,кін</sub> = t<sub>поч</sub> + τ<sub>геом</sub>')}${formula('8.2','t<sub>влас,поч</sub> = max(t<sub>геом,кін</sub>, t<sub>доступ</sub>)')}${formula('8.3','t<sub>влас,кін</sub> = t<sub>влас,поч</sub> + τ<sub>проц</sub>')}${formula('8.4','t<sub>зовн,кін</sub> = t<sub>геом,кін</sub> + τ<sub>оч</sub> + τ<sub>проц</sub>','t — момент часу; τ — тривалість у годинах. Для власного виконання потрібні всі передумови.')}`;
export const holdFormulas=h=>`${formula('5.1','H<sub>оч.пост</sub> = (s<sub>контроль</sub> − e<sub>ремонт</sub>) · 0,5'+(h?.valid?`<div class="math-substitution">(${num(h.end)} − ${num(h.start)}) · 0,5 = ${num(h.bayHours)} посто-год</div>`:''),'Різниця номерів 30-хвилинних робочих інтервалів × 0,5 год. [B02, B03]')}${formula('5.2','T<sub>оч</sub> = t<sub>контроль,поч</sub> − t<sub>ремонт,кін</sub>'+(h?.valid?`<div class="math-substitution">${dateText(slotStart(h.end))} − ${dateText(slotEnd(h.start))} = ${num(h.calendarHours)} год</div>`:''),'Календарна різниця у годинах включає неробочий час. У (5.1) обід і ніч не входять, у (5.2) — входять.')}`;
